version: 2

before:
  hooks:
    # Fetch and stage bird binaries so release archives can include them.
    - python3 scripts/vendor_bird.py

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/guzus/birdy/cmd.version={{.Version}}
      - -X github.com/guzus/birdy/cmd.commit={{.Commit}}
      - -X github.com/guzus/birdy/cmd.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: "bundled/bird/bird_{{ .Os }}_{{ .Arch }}{{ if eq .Os \"windows\" }}.exe{{ end }}"
        dst: "bird_{{ .Os }}_{{ .Arch }}{{ if eq .Os \"windows\" }}.exe{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: guzus
      name: homebrew-tap
    homepage: "https://github.com/guzus/birdy"
    description: "Multi-account proxy for the bird CLI to reduce rate-limit risk"
    license: "MIT"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
